# SPDX-FileCopyrightText: 2024 Foundation Devices Inc.
#
# SPDX-License-Identifier: MIT

[package]
name = "tor"
version = "0.0.9"
authors = ["Igor Cota <igor@foundation.xyz>"]
edition = "2021"

[lib]
crate-type = ["cdylib", "staticlib"]

[dependencies]
lazy_static = "1.5"
tokio = { version = "1", features = ["full"] }
arti-client = { version = "0.36.0", features = ["static", "onion-service-client"] }
arti = { version = "1.7.0", features = ["experimental-api", "static"] }
tor-rtcompat = { version = "0.36.0", features = ["static"] }
tor-config = "0.36.0"
log = "0.4.28"
#android_log-sys = "0.3.1"
rlimit = "0.10.2"
anyhow = "1.0.100"
time = "0.3.44"
tracing = "0.1.40"
tracing-subscriber = { version = "0.3.18", features = ["fmt", "tracing-log", "env-filter"] }
[target.'cfg(target_os = "android")'.dependencies]
tracing-android = "0.2.0"

[build-dependencies]
cbindgen = "=0.24.3"
