name: weblibre
description: "The Privacy-Focused & AI-Powered Research Browser"
publish_to: 'none'
resolution: workspace
version: 0.9.31-alpha-5+34

environment:
  sdk: '>=3.8.0 <4.0.0'

dependencies:
  animated_tree_view: ^2.3.0
  background_fetch: ^1.5.0
  collection: ^1.19.1
  convert: ^3.1.2
  copy_with_extension: ^10.0.1
  country_codes: ^3.3.0
  country_flags: ^4.1.1
  cryptography_flutter: ^2.3.4
  drift: ^2.30.0
  drift_dev: ^2.30.0
  dynamic_color: ^1.8.1
  exceptions: ^0.6.1
  fading_scroll: ^0.9.1
  fancy_password_field: ^2.0.8
  fast_equatable: ^1.3.1
  file_picker: ^10.3.8
  flutter:
    sdk: flutter
  flutter_auto_size_text: ^4.1.0
  flutter_hooks: ^0.21.3+1
  flutter_markdown: ^0.7.7+1
  flutter_material_design_icons: ^1.1.7447
  flutter_mozilla_components:
    path: ../packages/flutter_mozilla_components
  flutter_reorderable_grid_view: ^5.5.2
  flutter_slidable: ^4.0.3
  flutter_svg: ^2.2.3
  flutter_tor:
    path: ../packages/flutter_tor
  go_router: ^17.0.1
  google_fonts: ^6.3.3
  graphview: ^1.5.1
  home_widget: ^0.8.1
  hooks_riverpod: ^3.1.0
  html: ^0.15.6
  http: ^1.6.0
  intl: ^0.20.2
  json_annotation: ^4.9.0
  lexo_rank:
    git:
      url: https://github.com/FaFre/lexo_rank.git
  local_auth: ^3.0.0
  locale_resolver:
    path: ../packages/locale_resolver
  logger: ^2.6.2
  markdown: ^7.3.0
  mime: ^2.0.0
  nullability: ^1.0.0
  package_info_plus: ^9.0.0
  path: ^1.9.1
  path_provider: ^2.1.5
  permission_handler: ^12.0.1
  pretty_qr_code: ^3.5.0
  quick_actions: ^1.1.0
  riverpod: ^3.1.0
  riverpod_annotation: ^4.0.0
  rss_dart: ^1.0.14
  rxdart: ^0.28.0
  secure_archive:
    git:
      url: https://github.com/FaFre/secure_archive.git
      path: packages/secure_archive
  share_plus: ^12.0.1
  simple_intent_receiver:
    path: ../packages/simple_intent_receiver
  skeletonizer: ^2.1.2
  sliver_tools: ^0.2.12
  smooth_page_indicator: ^2.0.1
  socks5_proxy: ^2.1.1
  speech_to_text_google_dialog: 
    git:
      url: https://github.com/FaFre/speech_to_text_google_dialog.git
  sqlite3: ^2.9.4
  sqlite3_flutter_libs: ^0.5.41
  synchronized: ^3.4.0
  text_scroll: ^0.2.1
  timeago: ^3.7.1
  uri_to_file:
    git:
      url: https://github.com/FaFre/uri-to-file.git
  url_launcher: ^6.3.2
  uuid: ^4.5.2

dev_dependencies:
  build_runner: ^2.10.4
  copy_with_extension_gen: ^10.0.1
  custom_lint: ^0.8.1
  dependency_validator: ^5.0.3
  fast_equatable_lint: ^0.5.0
  flutter_launcher_icons: ^0.14.4
  flutter_test:
    sdk: flutter
  go_router_builder: ^4.1.3
  json_serializable: ^6.11.2
  lint: ^2.8.0
  mockito: ^5.4.4
  riverpod_generator: ^4.0.0+1
  riverpod_lint: ^3.1.0

flutter:
  uses-material-design: true
  assets:
    - assets/bangs/
    - assets/fonts/
    - assets/icon/
    - assets/images/
    - assets/landing/
    - assets/preferences/
  fonts:
    - family: TorIcons
      fonts:
        - asset: assets/fonts/tor-icons.ttf

flutter_launcher_icons:
  android: "launcher_icon"
  image_path: "assets/icon/icon.png"
  adaptive_icon_foreground: "assets/icon/icon.png"
  adaptive_icon_monochrome: "assets/icon/icon.png"
  adaptive_icon_foreground_inset: 25
  adaptive_icon_background: "#FF000000"
